# -*- coding: utf-8 -*-
"""Audio _Lyrics_Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEfcvhh8qt3FfDH9Ttj_7pd0CGeEvhKr
"""

#Installing Necessary Libraries #to install OpenAI's Whisper and FFmpeg, which are required for high-quality audio transcription
!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

import os
import whisper
from google.colab import drive

# 1. Mount Drive (force remount to refresh the file system)
drive.mount('/content/drive', force_remount=True)

# 2. Paths
AUDIO_PATH = '/content/drive/MyDrive/Music'
SAVE_PATH = '/content/drive/MyDrive/Lyrics_Output'

# 3. Load Model (Medium is recommended for English + Bangla mix)
model = whisper.load_model("medium")

# 4. RECURSIVE SEARCH: This explores all subfolders automatically
print("Searching for songs in all subfolders...")
for root, dirs, files in os.walk(AUDIO_PATH):
    for filename in files:
        if filename.lower().endswith(('.mp3', '.wav', '.m4a')):
            # Full path to the audio file
            audio_file_path = os.path.join(root, filename)

            # Create a matching genre folder in your Lyrics_Output
            # This keeps your 'Rock', 'Pop', etc. folders organized
            relative_folder = os.path.relpath(root, AUDIO_PATH)
            target_dir = os.path.join(SAVE_PATH, relative_folder)

            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

            print(f"Transcribing [{relative_folder}]: {filename}")

            # Transcription step
            result = model.transcribe(audio_file_path)

            # Save as .txt file with the same name as the song
            text_filename = os.path.splitext(filename)[0] + ".txt"
            with open(os.path.join(target_dir, text_filename), "w", encoding="utf-8") as f:
                f.write(result['text'])

print("\nSuccess! Your lyrics are now perfectly organized by genre in Drive.")

import os
import whisper
from google.colab import drive

# 1. Standard Setup
drive.mount('/content/drive', force_remount=True)
model = whisper.load_model("medium")

# 2. Define your folders
AUDIO_PATH = '/content/drive/MyDrive/Music'
SAVE_PATH = '/content/drive/MyDrive/Lyrics_Output'

# 3. The "Smart" Resuming Loop
for root, dirs, files in os.walk(AUDIO_PATH):
    for filename in files:
        if filename.lower().endswith(('.mp3', '.wav', '.m4a')):
            # Prepare the output path
            text_filename = os.path.splitext(filename)[0] + ".txt"
            relative_folder = os.path.relpath(root, AUDIO_PATH)
            target_dir = os.path.join(SAVE_PATH, relative_folder)
            save_file_path = os.path.join(target_dir, text_filename)

            # THE SKIP LOGIC: If the file already exists, don't rerun it!
            if os.path.exists(save_file_path):
                print(f"Skipping (Already Done): {filename}")
                continue

            # Create folder and transcribe ONLY if missing
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

            print(f"Resuming Conversion: {filename}...")
            audio_file_path = os.path.join(root, filename)
            try:
                result = model.transcribe(audio_file_path)

                with open(save_file_path, "w", encoding="utf-8") as f:
                    f.write(result['text'])
            except RuntimeError as e:
                print(f"Error processing {filename}: {e}. Skipping this file.")

print("All audio files have been converted to lyrics!")