# -*- coding: utf-8 -*-
"""CSE425_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBW8TI4IQCyNKPf0NlyZgL0-ERP-DZhD
"""

#1
!pip install librosa matplotlib numpy

#2
from google.colab import drive; drive.mount('/content/drive', force_remount=True)

#3

import os
import librosa
import numpy as np
from google.colab import drive

# 1. Mount Drive
drive.mount('/content/drive', force_remount=True)

# 2. Paths
AUDIO_PATH = '/content/drive/MyDrive/Music'
SAVE_PATH = '/content/drive/MyDrive/Audio_Features'

if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

# 3. Parameters for the "Medium Task"
N_MELS = 128  # Resolution of the spectrogram
DURATION = 30 # We'll take the first 30 seconds of each song

print("Starting audio feature extraction...")

for root, dirs, files in os.walk(AUDIO_PATH):
    for filename in files:
        if filename.lower().endswith(('.mp3', '.wav', '.m4a')):

            # Create subfolders for genres
            relative_folder = os.path.relpath(root, AUDIO_PATH)
            target_dir = os.path.join(SAVE_PATH, relative_folder)
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

            # Check if already processed
            feature_filename = os.path.splitext(filename)[0] + ".npy"
            save_file_path = os.path.join(target_dir, feature_filename)

            if os.path.exists(save_file_path):
                print(f"Skipping: {filename}")
                continue

            try:
                print(f"Processing audio: {filename}")
                # Load audio (automatically resamples to 22050Hz)
                y, sr = librosa.load(os.path.join(root, filename), duration=DURATION)

                # Create the Mel-Spectrogram
                S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=N_MELS)

                # Convert to log scale (decibels) for better ML performance
                S_dB = librosa.power_to_db(S, ref=np.max)

                # Save as a numpy array
                np.save(save_file_path, S_dB)

            except Exception as e:
                print(f"Error processing {filename}: {e}")

print("\nSuccess! Your audio 'fingerprints' are saved in Audio_Features.")

#4
###################
!pip install sentence-transformers

#5
import os
import numpy as np
from sentence_transformers import SentenceTransformer
from google.colab import drive

# 1. Setup
drive.mount('/content/drive', force_remount=True)
TEXT_PATH = '/content/drive/MyDrive/Lyrics_Output'
SAVE_PATH = '/content/drive/MyDrive/Text_Features'

if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

# 2. Load Multilingual BERT Model
# This model is great for English + Bangla mix!
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

print("Starting text embedding extraction...")

for root, dirs, files in os.walk(TEXT_PATH):
    for filename in files:
        if filename.endswith('.txt'):

            # Create subfolders for genres
            relative_folder = os.path.relpath(root, TEXT_PATH)
            target_dir = os.path.join(SAVE_PATH, relative_folder)
            if not os.path.exists(target_dir):
                os.makedirs(target_dir)

            # Check if already processed
            feature_filename = os.path.splitext(filename)[0] + ".npy"
            save_file_path = os.path.join(target_dir, feature_filename)

            if os.path.exists(save_file_path):
                print(f"Skipping: {filename}")
                continue

            try:
                # Read the lyrics
                with open(os.path.join(root, filename), 'r', encoding='utf-8') as f:
                    lyrics_text = f.read()

                if not lyrics_text.strip():
                    continue

                print(f"Embedding lyrics: {filename}")

                # Convert text to a vector (Embedding)
                embedding = model.encode(lyrics_text)

                # Save as a numpy array
                np.save(save_file_path, embedding)

            except Exception as e:
                print(f"Error processing {filename}: {e}")

print("\nSuccess! Your text embeddings are saved in Text_Features.")

########## CELL 6: CREATE DATASET CSV ##########

import os
import csv

AUDIO_DIR = '/content/drive/MyDrive/Audio_Features'
TEXT_DIR  = '/content/drive/MyDrive/Text_Features'
CSV_PATH  = '/content/drive/MyDrive/dataset.csv'

rows = []

for genre in os.listdir(AUDIO_DIR):
    audio_genre_path = os.path.join(AUDIO_DIR, genre)
    text_genre_path  = os.path.join(TEXT_DIR, genre)

    if not os.path.isdir(audio_genre_path):
        continue
    if not os.path.isdir(text_genre_path):
        continue

    for file in os.listdir(audio_genre_path):
        if file.endswith('.npy'):
            audio_path = os.path.join(audio_genre_path, file)
            text_path  = os.path.join(text_genre_path, file)

            if os.path.exists(text_path):
                rows.append([audio_path, text_path, genre])

print(f"Total paired samples: {len(rows)}")

with open(CSV_PATH, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['audio_path', 'text_path', 'genre'])
    writer.writerows(rows)

print(f"CSV saved at: {CSV_PATH}")

#STAGE 1 — AUDIO AUTOENCODER
########## CELL 7: AUDIO DATASET (FROM CSV) ##########

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
import csv

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

FIXED_AUDIO_SIZE = 128 * 1292  # Match your Mel-spectrogram size
CSV_PATH = '/content/drive/MyDrive/dataset.csv'

class AudioDataset(Dataset):
    def __init__(self, csv_path):
        self.audio_files = []
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.audio_files.append(row['audio_path'])

    def __len__(self):
        return len(self.audio_files)

    def __getitem__(self, idx):
        x = np.load(self.audio_files[idx]).flatten()

        if len(x) > FIXED_AUDIO_SIZE:
            x = x[:FIXED_AUDIO_SIZE]
        else:
            x = np.pad(x, (0, FIXED_AUDIO_SIZE - len(x)))

        # Normalize
        x = (x - x.min()) / (x.max() - x.min() + 1e-8)

        return torch.FloatTensor(x)

########## CELL 8: AUDIO AUTOENCODER ##########

import torch.nn as nn
from torch.utils.data import DataLoader

# Training parameters
EPOCHS = 3   # short
BATCH_SIZE = 16
LEARNING_RATE = 1e-4

dataset = AudioDataset(CSV_PATH)
loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# Simple autoencoder
class AudioAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(FIXED_AUDIO_SIZE, 512),
            nn.ReLU(),
            nn.Linear(512, 128)
        )
        self.decoder = nn.Sequential(
            nn.Linear(128, 512),
            nn.ReLU(),
            nn.Linear(512, FIXED_AUDIO_SIZE)
        )

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)

model = AudioAutoencoder().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
criterion = nn.MSELoss()

print("Training Stage 1: Audio Autoencoder")

for epoch in range(EPOCHS):
    total_loss = 0
    for x in loader:
        x = x.to(device)
        optimizer.zero_grad()
        recon = model(x)
        loss = criterion(recon, x)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.6f}")

# Save the encoder only
torch.save(model.encoder.state_dict(),
           "/content/drive/MyDrive/audio_encoder_stage1.pth")
print("Stage 1 complete — audio encoder saved")

########## CELL 9: TEXT DATASET ##########

import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import csv

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CSV_PATH = '/content/drive/MyDrive/dataset.csv'

class TextDataset(Dataset):
    def __init__(self, csv_path):
        self.text_files = []
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.text_files.append(row['text_path'])

    def __len__(self):
        return len(self.text_files)

    def __getitem__(self, idx):
        x = np.load(self.text_files[idx])
        # Safe min-max normalization
        xmin, xmax = x.min(), x.max()
        if xmax - xmin > 0:
            x = (x - xmin) / (xmax - xmin)
        else:
            x = np.zeros_like(x)
        return torch.FloatTensor(x)

########## CELL 10: TEXT AUTOENCODER MODEL ##########

import torch.nn as nn

TEXT_DIM = 384        # Size of MiniLM embeddings
TEXT_LATENT_DIM = 64  # Latent dimension

class TextAutoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(TEXT_DIM, 128),
            nn.ReLU(),
            nn.Linear(128, TEXT_LATENT_DIM)
        )
        self.decoder = nn.Sequential(
            nn.Linear(TEXT_LATENT_DIM, 128),
            nn.ReLU(),
            nn.Linear(128, TEXT_DIM)
        )

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)

########## CELL 11: TRAIN TEXT AUTOENCODER ##########

dataset_text = TextDataset(CSV_PATH)
loader_text = DataLoader(dataset_text, batch_size=16, shuffle=True)

model_text = TextAutoencoder().to(device)
optimizer = torch.optim.Adam(model_text.parameters(), lr=1e-4)
criterion = nn.MSELoss()

print("Training Stage 2: Text Autoencoder")

num_epochs = 20  # Small number for sanity check
for epoch in range(num_epochs):
    total_loss = 0
    for x in loader_text:
        x = x.to(device)
        optimizer.zero_grad()
        recon = model_text(x)
        loss = criterion(recon, x)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader_text):.6f}")

# Save the encoder only
torch.save(model_text.encoder.state_dict(),
           '/content/drive/MyDrive/text_encoder_stage2.pth')
print("Stage 2 complete — text encoder saved")

########## CELL 12: MULTIMODAL DATASET ##########

import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import csv

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CSV_PATH = '/content/drive/MyDrive/dataset.csv'

FIXED_AUDIO_SIZE = 128 * 1292  # Stage 1 Mel-spectrogram flattened
TEXT_DIM = 384                 # Stage 2 embedding size

class MultimodalDataset(Dataset):
    def __init__(self, csv_path):
        self.samples = []
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.samples.append((row['audio_path'], row['text_path'], row['genre']))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        # Load audio
        audio = np.load(self.samples[idx][0]).flatten()
        if len(audio) > FIXED_AUDIO_SIZE:
            audio = audio[:FIXED_AUDIO_SIZE]
        else:
            audio = np.pad(audio, (0, FIXED_AUDIO_SIZE - len(audio)))
        audio_min, audio_max = audio.min(), audio.max()
        if audio_max - audio_min > 0:
            audio = (audio - audio_min) / (audio_max - audio_min)
        else:
            audio = np.zeros_like(audio)

        # Load text
        text = np.load(self.samples[idx][1])
        text_min, text_max = text.min(), text.max()
        if text_max - text_min > 0:
            text = (text - text_min) / (text_max - text_min)
        else:
            text = np.zeros_like(text)

        # Combine features
        hybrid_feature = np.concatenate([audio, text])
        return torch.FloatTensor(hybrid_feature), self.samples[idx][2]

########## CELL 13: MULTIMODAL VAE ##########

import torch.nn as nn

HYBRID_DIM = FIXED_AUDIO_SIZE + TEXT_DIM
LATENT_DIM = 128  # Can adjust smaller/larger

class MultimodalVAE(nn.Module):
    def __init__(self, input_dim, latent_dim):
        super().__init__()
        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Linear(512, latent_dim * 2)  # mu + logvar
        )
        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 512),
            nn.ReLU(),
            nn.Linear(512, input_dim)
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar).clamp(max=10)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        h = self.encoder(x)
        mu, logvar = torch.chunk(h, 2, dim=-1)
        z = self.reparameterize(mu, logvar)
        return self.decoder(z), mu, logvar

########## CELL 14: INIT DATASET AND MODEL ##########

from torch.utils.data import DataLoader
import torch.optim as optim

dataset = MultimodalDataset(CSV_PATH)
loader = DataLoader(dataset, batch_size=8, shuffle=True)

first_item, _ = dataset[0]
model = MultimodalVAE(input_dim=len(first_item), latent_dim=LATENT_DIM).to(device)
optimizer = optim.Adam(model.parameters(), lr=5e-5)

print(f"Multimodal VAE ready. Total input dim: {len(first_item)}, Latent dim: {LATENT_DIM}")

########## CELL 15: TRAIN MULTIMODAL VAE ##########

criterion = nn.MSELoss()  # stable for reconstruction
num_epochs = 10           # short sanity check

print(f"Starting Stage 3 training on {device}...")

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch_idx, (data, _) in enumerate(loader):
        data = data.to(device)
        optimizer.zero_grad()
        recon, mu, logvar = model(data)
        recon_loss = criterion(recon, data)
        kld_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
        loss = recon_loss + 0.01 * kld_loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss/len(loader):.6f}")

# Save full model
torch.save(model.state_dict(),
           '/content/drive/MyDrive/multimodal_vae_stage3.pth')
print("Stage 3 complete — Multimodal VAE saved")

# ########## CELL 16: CLUSTERING EVALUATION ##########

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score

# Extract latent vectors
model.eval()
latents = []
genres = []

with torch.no_grad():
    for data, g in loader:
        data = data.to(device)
        h = model.encoder(data)
        mu, logvar = torch.chunk(h, 2, dim=-1)
        latents.append(mu.cpu().numpy())
        genres.extend(g)

latents = np.vstack(latents)

# Perform clustering (KMeans with number of genres)
n_clusters = len(set(genres))
kmeans = KMeans(n_clusters=n_clusters, random_state=42).fit(latents)
labels = kmeans.labels_

sil_score = silhouette_score(latents, labels)
ch_score  = calinski_harabasz_score(latents, labels)

print(f"Silhouette Score: {sil_score:.4f}")
print(f"Calinski-Harabasz Index: {ch_score:.4f}")

import torch
from torch.utils.data import Dataset
import numpy as np
import csv

FIXED_AUDIO_SIZE = 128 * 1292
CSV_PATH = '/content/drive/MyDrive/dataset.csv'

class AudioVAEDataset(Dataset):
    def __init__(self, csv_path):
        self.audio_files = []
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.audio_files.append(row['audio_path'])

    def __len__(self):
        return len(self.audio_files)

    def __getitem__(self, idx):
        x = np.load(self.audio_files[idx]).flatten()

        if len(x) > FIXED_AUDIO_SIZE:
            x = x[:FIXED_AUDIO_SIZE]
        else:
            x = np.pad(x, (0, FIXED_AUDIO_SIZE - len(x)))

        x = (x - x.min()) / (x.max() - x.min() + 1e-8)
        return torch.FloatTensor(x)

import torch.nn as nn
import torch

LATENT_DIM = 64

class AudioVAE(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Linear(FIXED_AUDIO_SIZE, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU()
        )

        self.fc_mu = nn.Linear(256, LATENT_DIM)
        self.fc_logvar = nn.Linear(256, LATENT_DIM)

        self.decoder = nn.Sequential(
            nn.Linear(LATENT_DIM, 256),
            nn.ReLU(),
            nn.Linear(256, 512),
            nn.ReLU(),
            nn.Linear(512, FIXED_AUDIO_SIZE)
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        h = self.encoder(x)
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        z = self.reparameterize(mu, logvar)
        recon = self.decoder(z)
        return recon, mu, logvar

from torch.utils.data import DataLoader
import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

dataset = AudioVAEDataset(CSV_PATH)
loader = DataLoader(dataset, batch_size=16, shuffle=True)

model = AudioVAE().to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.MSELoss()

EPOCHS = 10

for epoch in range(EPOCHS):
    total_loss = 0
    for x in loader:
        x = x.to(device)
        optimizer.zero_grad()

        recon, mu, logvar = model(x)
        recon_loss = criterion(recon, x)
        kl_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())

        loss = recon_loss + 0.01 * kl_loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.6f}")

torch.save(model.state_dict(),
           '/content/drive/MyDrive/audio_vae_easy.pth')

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score
import numpy as np

X = []
for i in range(len(dataset)):
    X.append(dataset[i].numpy())

X = np.array(X)

pca = PCA(n_components=50)
X_pca = pca.fit_transform(X)

kmeans = KMeans(n_clusters=5, random_state=42)
labels = kmeans.fit_predict(X_pca)

print("PCA + KMeans")
print("Silhouette:", silhouette_score(X_pca, labels))
print("Calinski-Harabasz:", calinski_harabasz_score(X_pca, labels))

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X_pca)

plt.figure(figsize=(6,6))
plt.scatter(X_tsne[:,0], X_tsne[:,1], c=labels, cmap='tab10')
plt.title("PCA + KMeans (t-SNE)")
plt.show()

import torch
from torch.utils.data import Dataset
import numpy as np
import csv

# Define the fixed width for the spectrograms. This value comes from N_MELS (128) * FIXED_AUDIO_WIDTH (1292)
# from the previous cells' definitions (e.g., FIXED_AUDIO_SIZE = 128 * 1292).
# We are setting the number of time frames to 1292.
FIXED_SPECTROGRAM_WIDTH = 1292

FIXED_TIME = 1292  # all spectrograms will have same time length

class ConvAudioDataset(Dataset):
    def __init__(self, csv_path):
        self.audio_files = []
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.audio_files.append(row['audio_path'])

    def __len__(self):
        return len(self.audio_files)

    def __getitem__(self, idx):
        x = np.load(self.audio_files[idx])  # shape: (128, time)

        # Normalize
        x = (x - x.min()) / (x.max() - x.min() + 1e-8)

        # Fix time dimension
        if x.shape[1] > FIXED_TIME:
            x = x[:, :FIXED_TIME]
        else:
            pad = FIXED_TIME - x.shape[1]
            x = np.pad(x, ((0, 0), (0, pad)))

        return torch.FloatTensor(x).unsqueeze(0)

sample = ConvAudioDataset(CSV_PATH)[0]
print(sample.shape)

class ConvAudioVAE(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Conv2d(1, 16, 3, stride=2, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, 32, 3, stride=2, padding=1),
            nn.ReLU()
        )

        self.fc_mu = nn.Linear(32*32*323, 64)
        self.fc_logvar = nn.Linear(32*32*323, 64)

        self.fc_dec = nn.Linear(64, 32*32*323)

        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(32, 16, 3, stride=2, padding=1, output_padding=1),
            nn.ReLU(),
            nn.ConvTranspose2d(16, 1, 3, stride=2, padding=1, output_padding=1)
        )

    def forward(self, x):
        h = self.encoder(x)
        h = h.view(h.size(0), -1)
        mu, logvar = self.fc_mu(h), self.fc_logvar(h)
        z = mu + torch.randn_like(mu) * torch.exp(0.5 * logvar)
        h_dec = self.fc_dec(z).view(-1, 32, 32, 323)
        return self.decoder(h_dec), mu, logvar

from torch.utils.data import DataLoader
import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

conv_dataset = ConvAudioDataset(CSV_PATH)
conv_loader = DataLoader(conv_dataset, batch_size=8, shuffle=True)

conv_model = ConvAudioVAE().to(device)
optimizer = optim.Adam(conv_model.parameters(), lr=1e-4)
criterion = nn.MSELoss()

EPOCHS = 15
beta = 1.0   # will change later for Beta-VAE

print("Training Conv Audio VAE...")

for epoch in range(EPOCHS):
    total_loss = 0
    for x in conv_loader:
        x = x.to(device)

        optimizer.zero_grad()
        recon, mu, logvar = conv_model(x)

        recon_loss = criterion(recon, x)
        kl_loss = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())

        loss = recon_loss + beta * kl_loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {total_loss/len(conv_loader):.6f}")

torch.save(conv_model.state_dict(),
           "/content/drive/MyDrive/conv_audio_vae_medium.pth")

print("Conv Audio VAE training complete.")

conv_model.eval()

latent_vectors = []

with torch.no_grad():
    for x in conv_loader:
        x = x.to(device)
        h = conv_model.encoder(x)
        h = h.view(h.size(0), -1)
        mu = conv_model.fc_mu(h)
        latent_vectors.append(mu.cpu().numpy())

latent_vectors = np.vstack(latent_vectors)

print("Latent feature shape:", latent_vectors.shape)

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score

# KMeans
kmeans = KMeans(n_clusters=5, random_state=42)
kmeans_labels = kmeans.fit_predict(latent_vectors)

# Agglomerative
agglo = AgglomerativeClustering(n_clusters=5)
agglo_labels = agglo.fit_predict(latent_vectors)

# DBSCAN
dbscan = DBSCAN(eps=1.5, min_samples=5)
dbscan_labels = dbscan.fit_predict(latent_vectors)

print("KMeans Silhouette:", silhouette_score(latent_vectors, kmeans_labels))
print("Agglomerative Silhouette:", silhouette_score(latent_vectors, agglo_labels))
# DBSCAN metrics (only if more than 1 cluster)
unique_labels = set(dbscan_labels)

if len(unique_labels) > 1 and (-1 in unique_labels and len(unique_labels) > 2 or -1 not in unique_labels):
    print("DBSCAN Silhouette:", silhouette_score(latent_vectors, dbscan_labels))
    print("DBSCAN DBI:", davies_bouldin_score(latent_vectors, dbscan_labels))
else:
    print("DBSCAN did not find enough clusters for evaluation.")


print("KMeans DBI:", davies_bouldin_score(latent_vectors, kmeans_labels))
print("Agglomerative DBI:", davies_bouldin_score(latent_vectors, agglo_labels))

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, random_state=42)
latent_2d = tsne.fit_transform(latent_vectors)

plt.figure(figsize=(7,7))
plt.scatter(latent_2d[:,0], latent_2d[:,1], c=kmeans_labels, cmap='tab10')
plt.title("Conv Audio VAE Latent Space (t-SNE + KMeans)")
plt.colorbar()
plt.show()

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

# Reduce latent vectors to 2D
tsne = TSNE(n_components=2, random_state=42)
latents_2d = tsne.fit_transform(latent_vectors)

# Map genres to integers for coloring
unique_genres = list(set(genres))
genre_to_int = {g:i for i,g in enumerate(unique_genres)}
colors = [genre_to_int[g] for g in genres]

# Plot
plt.figure(figsize=(10,8))
scatter = plt.scatter(latents_2d[:,0], latents_2d[:,1], c=colors, cmap='tab10', alpha=0.7)
plt.legend(handles=scatter.legend_elements()[0], labels=unique_genres)
plt.title("t-SNE of VAE Latent Space")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

# Create a DataFrame
df = pd.DataFrame({'cluster': kmeans_labels, 'genre': genres})

# Count of samples per cluster per genre
cluster_genre = df.groupby(['cluster', 'genre']).size().unstack(fill_value=0)

# Plot as heatmap
plt.figure(figsize=(10,6))
sns.heatmap(cluster_genre, annot=True, fmt="d", cmap="YlGnBu")
plt.title("Cluster distribution over Genres")
plt.ylabel("Cluster")
plt.xlabel("Genre")
plt.show()

# Pick 5 random latent vectors
import torch

model.eval()
sample_indices = np.random.choice(len(latent_vectors), 5, replace=False)

for idx in sample_indices:
    latent = torch.FloatTensor(latent_vectors[idx]).to(device)
    # Pass through decoder
    recon = model.decoder(latent.unsqueeze(0)).cpu().detach().numpy().flatten()

    # Reshape to original hybrid size (audio + text)
    audio_recon = recon[:FIXED_AUDIO_SIZE].reshape(128, -1)

    plt.figure(figsize=(8,3))
    plt.title(f"Reconstructed Spectrogram Sample {idx}")
    plt.imshow(audio_recon, origin='lower', aspect='auto', cmap='magma')
    plt.colorbar()
    plt.show()

from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, calinski_harabasz_score

# Apply PCA to latent vectors (or raw features)
pca = PCA(n_components=LATENT_DIM)
latent_pca = pca.fit_transform(latent_vectors)

# KMeans on PCA
kmeans_pca = KMeans(n_clusters=len(unique_genres), random_state=42).fit(latent_pca)
labels_pca = kmeans_pca.labels_

print("Baseline (PCA + KMeans) Silhouette:", silhouette_score(latent_pca, labels_pca))
print("Baseline (PCA + KMeans) Calinski-Harabasz:", calinski_harabasz_score(latent_pca, labels_pca))

import pandas as pd

df_latent = pd.DataFrame(latent_vectors)
df_latent['genre'] = genres
df_latent['kmeans_cluster'] = kmeans_labels
df_latent.to_csv("/content/drive/MyDrive/latent_features_clusters.csv", index=False)